### ISSUE TITLE
HIPSPARSE_STATUS_INVALID_VALUE from hipsparseSpGEMM_compute

### ISSUE THREAD

**Issue by jinz2014** [ROCm/hipSPARSE#387] opened 2023-08-30 22:32 UTC
I migrated a CUDA program that executes the cusparseSpGEMM function.  While the CUDA program runs without errors, the HIP program reports the following error.  I am not sure if the error is caused by the library or subtle differences between the API functions I am not aware of. Thank you for taking a look at the program. 

To reproduce:

cd into the directory "spmm-hip" in https://github.com/zjin-lcf/HeCBench/tree/master/spmm-hip
make
./main 1024 1024 1024 1024 1024 1 1
hipSPARSE error: HIPSPARSE API failed at line 261 with error: HIPSPARSE_STATUS_INVALID_VALUE

**Comment by jsandham** [comment] 2023-09-08 13:53
@jinz2014 Thanks for bringing this to our attention. Ill take a look and get back to you.

**Comment by jsandham** [comment] 2023-09-15 20:38
I have identified the issue. If you replace this:

CHECK_HIPSPARSE( hipsparseCreateCsr(&matC, A_num_rows, B_num_cols, 0,
                                    NULL, NULL, NULL,
                                    HIPSPARSE_INDEX_32I, HIPSPARSE_INDEX_32I,
                                    HIPSPARSE_INDEX_BASE_ZERO, HIP_R_32F) )
                                    
at line 219 of your example with:

CHECK_HIPSPARSE( hipsparseCreateCsr(&matC, A_num_rows, B_num_cols, 0,
                                    dC_offsets, NULL, NULL,
                                    HIPSPARSE_INDEX_32I, HIPSPARSE_INDEX_32I,
                                    HIPSPARSE_INDEX_BASE_ZERO, HIP_R_32F) )
                                    
it works. The issue is hipsparse assumes that the row ptr array has been set (as there is no reason to not set it given we know before hand its size). Apparently in cusparse setting it is not required. I will need to modify the hipsparse code to allow for this use case.

**Comment by jinz2014** [comment] 2023-09-15 22:07
I got the same error with the code change. Thanks.

**Comment by jsandham** [comment] 2024-04-04 20:58
This should now be fixed in develop branches for hipsparse and rocsparse. Fix will go into upcoming 6.2 release.

**Closed by jsandham** 2024-04-04 20:58 UTC
